name = "graphql-edge-caching"
type = "javascript"
compatibility_date = "2021-12-13"
workers_dev = true
account_id = "f6774eabe4f23feac14dbcb39f56e63d"

kv_namespaces = [{ binding = "RESPONSES", id = "fd9f8c2b29d841918dbdf0e8d825dd21", preview_id = "fd9f8c2b29d841918dbdf0e8d825dd21"}]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./dist"
main = "./index.mjs"
